### ISSUE TITLE
Gradle DSL method not found

### ISSUE THREAD

**Issue by ulamnet** [MojRoid/PAD#1]
Hello , when I import this project in android studio , I get this error ;

Error:(84, 0) Gradle DSL method not found: 'exclude()'
Possible causes:<ul><li>The project 'PAD-master' may be using a version of Gradle that does not contain the method.
<a href="open.wrapper.file">Open Gradle wrapper file</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li>

How to fix ?

**Comment by MojRoid** [comment]
I've long abandoned this project so unfortunately I won't be able to look into this too deeply. I'm guessing it might be something to do with some of the library imports or your gradle version? > https://www.google.co.uk/search?q=Gradle+DSL+method+not+found%3A+%27exclude()%27
